#pragma once
#include <stdlib.h>
#include <fstream>
#include <iostream>
#include <sstream>
#include "includes/rapidxml.hpp"
#include "includes/rapidxml_iterators.hpp"
#include "includes/rapidxml_print.hpp"
#include "includes/rapidxml_utils.hpp"